# Generated by Django 2.0.5 on 2018-06-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.CharField(blank=True, max_length=2040, null=True),
        ),
    ]
